name: Lint Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get commits in PR
        id: commits
        run: |
          COMMITS=$(git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s")
          echo "$COMMITS" > commits.txt
          echo "Commits in PR:"
          cat commits.txt

      - name: Lint each commit message
        run: |
          while read line; do
            echo "Linting: $line"
            echo "$line" | npx commitlint
          done < commits.txt
